#include <iostream>
#include <cstdlib>
using namespace std;

//User-defined functions that return a value.
int hitCard();
int dealerCard();
int aceCheck(int drawnCard);

//User-defined functions that do not return a value.
void winLose(int result, int dealerResult);
void comparison(int value1, int value2);

int main()
{
	//Variables
	char choice, again;
	bool menu = true;
	int card = 0, finalHand, dealer;

	//Narration
	cout << "---------------------------------------------------------------" << endl;
	cout << "You approach the blackjack table hesitantly. The few" << endl;
	cout << "casino chips in your possession rattle quietly against" << endl;
	cout << "each other as you hold them lightly in your palm. You awkwardly" << endl;
	cout << "take a seat and place two chips down for your buy-in." << endl;
	cout << "---------------------------------------------------------------" << endl;

	//Game-flow loop
	while (menu == true){
		cout << "\n[ -Menu- ] | (h)it | (s)tay | (v)iew hand: " << endl;
		cin >> choice;

		switch(choice){
			case 'h':
			case 'H':
				card += aceCheck(hitCard());
				break;
			case 's':
			case 'S':
				finalHand = card;
				cout << "\n-------------------------" << endl;
				cout << "The Dealer draws 3 cards." << endl;
				cout << "-------------------------\n" << endl;
				dealer = dealerCard();
				comparison(card, dealer);
				winLose(finalHand, dealer);
				cout << "Play again?(y/n): " << endl;
				cin >> again;
					switch(again){
						case 'y':
						case 'Y':
							card = 0;
							cout << "-----------------------------------" << endl;
							cout << "You smirk, feigning confidence, and" << endl;
							cout << "place two more chips on the table." << endl;
							cout << "-----------------------------------" << endl;
							menu = true;
							break;
						case 'n':
						case 'N':
							card = 0;
							cout << "-----------------------------------" << endl;
							cout << "You quickly gather the remainder of" << endl;
							cout << "your chips, tip the dealer, and walk" << endl;
							cout << "briskly to the front to cash out." << endl;
							cout << "-----------------------------------" << endl;
							menu = false;
							break;		
						default:
							card = 0;
							menu = false;
							break;			
					}
				break;
			case 'v':
			case 'V':
				cout << "Your hand total is: [" << card << "]" << endl;
				break;
			default:
				cout << "----------------------------------------------" << endl;
				cout << "You suddenly come to a realization that you" << endl;
				cout << "have absolutely no idea how to play blackjack." << endl;
				cout << "You stand up, awkwardly nodding to the dealer" << endl;
				cout << "while gathering up your chips, and run towards" << endl;
				cout << "the nearest exit without looking back." << endl;
				cout << "----------------------------------------------" << endl;
				card = 0;
				menu = false;
				break;
		}

		
	}
	
	return 0;
}

//Function to generate and return a random number between 1 and 10
int hitCard()
{
	srand(time(0));
	int randomCard = rand() % 10 + 1;
	return randomCard;

}

//Function to generate 3 random numbers between 1 and 10, add them together, and return the value
int dealerCard()
{
	int theDealer = 0;
	srand(time(0));

	for(int i = 1; i < 4; i++){
		theDealer += hitCard();
		srand(time(0)); //Attempt to re-randomize the seed due to previous attempts yielding three of 
						//the same number each time since the loop is completed in under a second.
		
	}

	return theDealer;	
}

//Function to check the random number generated by the hitCard() function to see if it
//would be an "ace", which allows the player to change the value of the card as per the rules
//and return the value. Otherwise it simply returns the value of the random number.
int aceCheck(int drawnCard)
{
	int aceCheckResult;
	char aceChoice;

	if(drawnCard == 1){
		cout << "\nYou drew an ace!" << endl;
		cout << "Aces high[11] or low[1]? (h/l): " << endl;
		cin >> aceChoice;
			switch(aceChoice){
				case 'h':
				case 'H':
					aceCheckResult = 11;
					break;
				case 'l':
				case 'L':
					aceCheckResult = 1;
					break;
				default:
					aceCheckResult = 1;
					break;
			}
	}
	else{
		cout << "You drew a: [" << drawnCard << "]" << endl;
		aceCheckResult = drawnCard;
	}
	return aceCheckResult;
}

//Function that compares the player's hand to the dealer's hand, and also to the general rules
//and displays a message corresponding to the result of the ruling.
void winLose(int result, int dealerResult)
{
	if(result > 21){
		cout << "Sorry, you lose. (Hand greater than 21)\n" << endl;
	}
	else if(result <= 21 && result > dealerResult){
		cout << "You win! (Hand greater than Dealer)\n" << endl;
	}
	else if(result == dealerResult){
		cout << "Sorry, you lose. (Hand equal to Dealer, house wins)\n" << endl;
	}
	else if(result > 21 && dealerResult > 21){
		cout << "Sorry, you lose. (Hand greater than 21, Dealer greater than 21, house wins)\n" << endl;
	}
	else if(result < dealerResult && dealerResult <= 21){
		cout << "Sorry, you lose. (Dealer greater than Hand)\n" << endl;
	}
	else{
		cout << "You win! (Dealer greater than 21)\n" << endl;
	}

}

//Function that displays the current value of the player's hand in comparison to the dealer's.
void comparison(int value1, int value2)
{
	cout << "Your hand: [" << value1 << "]  |  Dealer hand: [" << value2 << "]\n" << endl;
}
